### ISSUE TITLE
Angular - build failing, due to TS compilation error

### ISSUE THREAD

**Issue by tanvi-cota** [cube-js/cube.js#220]
**Version:**
 "@cubejs-client/ngx": "^0.10.43"

**Steps To Reproduce**
- In the Angular8 application, when I try to do - 
                  `ng build --prod`
I get the below error

**Error**
ERROR in ./node_modules/@cubejs-client/ngx/src/module.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /Users/Git/node_modules/@cubejs-client/ngx/src/module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/Git/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:869:23)
    at plugin.done.then (/Users/Git/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by paveltiunov** [comment]
@tanvi-cota Hey Tanvi! Thanks for posting this! Finally got this working in 0.10.52. Could you please check?

**Comment by tanvi-cota** [comment]
@paveltiunov Tested on `10.10.55` and it seems to build correctly. Thanks!
