### ISSUE TITLE
Build failure after upgrade to 1.3.26: Cannot find module '@/utils/env'

### ISSUE THREAD

**Issue by tomdarmon-appstack** [cube-js/cube.js#9729]
Describe the bug
After the Cube Cloud version auto-upgraded from 1.3.18 to 1.3.26, the API started failing at build time with the following error:

javascript
Copy
Edit
Error: Cannot find module '@/utils/env'
This module was previously resolving correctly in version 1.3.18.

Downgrading back to 1.3.18 resolved the issue, but the initial failure broke our production environment.

Working: 1.3.18

Broken: 1.3.26

Am I the only one with this error?
